local widgets_path = icon_dir .. chosen_theme .. "/widgets/"

-- Define the image to load
theme.widget_ac                                 = widgets_path .. "ac.png"
theme.widget_battery                            = widgets_path .. "battery.png"
theme.widget_battery_low                        = widgets_path .. "battery_low.png"
theme.widget_battery_empty                      = widgets_path .. "battery_empty.png"
theme.widget_mem                                = widgets_path .. "mem.png"
theme.widget_cpu                                = widgets_path .. "cpu.png"
theme.widget_temp                               = widgets_path .. "temp.png"
theme.widget_net                                = widgets_path .. "net.png"
theme.widget_hdd                                = widgets_path .. "hdd.png"
theme.widget_music                              = widgets_path .. "note.png"
theme.widget_music_on                           = widgets_path .. "note_on.png"
theme.widget_vol                                = widgets_path .. "vol.png"
theme.widget_vol_low                            = widgets_path .. "vol_low.png"
theme.widget_vol_no                             = widgets_path .. "vol_no.png"
theme.widget_vol_mute                           = widgets_path .. "vol_mute.png"
theme.widget_mail                               = widgets_path .. "mail.png"
theme.widget_mail_on                            = widgets_path .. "mail_on.png"
